src/Entity/Contact.php
<?php

namespace App\Entity;

use App\Repository\ContactRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ContactRepository::class)
 */
class Contact
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="text")
     */
    private $message;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isSend;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getIsSend(): ?bool
    {
        return $this->isSend;
    }

    public function setIsSend(bool $isSend): self
    {
        $this->isSend = $isSend;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Repository\EvenementRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function index(EvenementRepository $evenementRepository): Response
    {
        return $this->render('home/index.html.twig', [
            'evenements' => $evenementRepository->lastFour(),
        ]);
    }
}

templates/home/evenements.html.twig
<h2>
    Nos evenement a venir
</h2>

{% for evenement in evenements %}

    <div class="col-12 col-md">

        <div class="row mt-4" id="even">

            <div class="col-3">
                <a href="{{ path('evenement-details', {'slug':evenement.slug}) }}">
                    <img src="{{ vich_uploader_asset(evenement, 'imageFile') }}" alt="" class="img-fluid"></a>
                </div>

                <div class="col-6">
                    <h3 class="text-center">
                        {{ evenement.nom }}
                    </h3>
                    <div class="font-even">
                        {{ evenement.description|u.truncate(200, '...', false) }}
                    </div>
                </div>

                <div class="col-3 text-center" id="even-border">
                    <div class="even-date">
                        <div>
							<i class="far fa-calendar-alt"></i>
						</div>
                        {{ evenement.dateDebut|date('d-m-Y') }}
                        au
                        {{ evenement.dateFin|date('d-m-Y') }}
                    </div>
                    <div class="even-adresse">
                        <div>
                            <div>
								<i class="fas fa-map-marked-alt"></i>
							</div>
                            {{ evenement.adresse }}
                        </div>
                        <div>
                            {{ evenement.codePostal }}
                            {{ evenement.ville }}
                        </div>
                    </div>
                    <div class="even-prix">
                        <div>
							<i class="far fa-money-bill-alt"></i>
						</div>
                        {{ evenement.prix }}
                        €
                    </div>
                </div>
                <div class="bouton-detail">
                    <a href="{{ path('evenement-details',{'slug': evenement.slug}) }}" id="bouton-detail">
                        detail
                    </a>
                </div>
            </div>
        </div>
    {% endfor %}
    

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}accueil{% endblock %}

{% block body %}
{% include "home/welcome.html.twig" %}
{% include "home/evenements.html.twig" %}
{% endblock %}

templates/home/welcome.html.twig
<div>
	<p>
		Lorem ipsum dolor sit, amet consectetur adipisicing elit. Fugiat dicta autem tempore facere dignissimos quod doloribus sit adipisci totam! Accusantium quidem nihil, blanditiis cupiditate et reprehenderit delectus labore doloremque aliquid?
				Aliquam sunt natus, veritatis officia odio nisi, maiores molestiae illo, fuga minus quod laboriosam. Quos eius corporis earum, dolor ut eos aliquid quidem optio sunt exercitationem libero autem quasi! Quisquam.
				Animi sit reiciendis ex voluptatum sequi nesciunt inventore, sunt atque, excepturi, optio repellendus. Accusamus deserunt nostrum totam, non reprehenderit veniam animi id inventore vel aliquid, repellendus dolore odio libero quaerat.
				Sit tempore hic nobis cum perspiciatis, nihil omnis ipsam illo animi, qui assumenda sed ipsum nam sint, accusantium atque? Dolores, deleniti ipsa maiores minima consectetur quisquam dignissimos expedita quaerat ab.
				Hic provident error ipsum, maxime sit quam perspiciatis. Fugiat ipsa commodi nam officiis dignissimos, aut quod enim fuga? Maxime corrupti inventore tempora quo debitis sit qui quos. Est, nemo laudantium.
				Sit corrupti odit eaque inventore exercitationem iste assumenda iusto accusamus. Qui, atque! Soluta deserunt accusantium explicabo, facilis magni, rem optio enim aliquam ipsa sunt, facere ipsam tempora culpa magnam temporibus!
				Atque voluptas suscipit temporibus quas, sed reprehenderit minus architecto et illum molestias dolore necessitatibus, tenetur nesciunt nihil non molestiae soluta. Dolores delectus voluptatibus voluptatum optio? Atque dolores ad amet iste.
				Laborum delectus consectetur pariatur illum assumenda dolore sequi cum accusantium distinctio expedita porro doloribus tenetur, necessitatibus voluptatem aliquam tempora voluptas unde quam optio quod placeat dolor modi deleniti. Magni, voluptatem!
				Nihil est hic dolore expedita porro? Doloribus in dolorem sequi quo, perferendis qui dolores rerum enim, eius magnam ad, earum sapiente minima sit quod cum repudiandae obcaecati neque consectetur iste?
				Velit adipisci minus totam excepturi vel id? Numquam esse, nesciunt pariatur dolorum nobis, cumque maxime a vel quidem ipsam qui, recusandae quisquam natus blanditiis minima consequatur. Odit labore ipsum vitae.
				Exercitationem adipisci distinctio illo doloremque, maiores iure necessitatibus! Minima recusandae quod aut ipsum, est dignissimos autem dolor debitis! Tenetur quam aut magni molestias ea eaque minima officiis officia pariatur temporibus?
				Sit nobis obcaecati assumenda. Veritatis iste dignissimos, doloremque ex blanditiis tempore? Nesciunt, ea. Magni voluptatem, aspernatur fugit vitae aperiam ipsum. Ullam laboriosam vel in fuga autem? Sint laboriosam eveniet illo.
				Ab quibusdam sit ipsum sunt unde aliquid quam veniam rerum excepturi voluptate eos qui magnam neque ad ratione repellat perspiciatis, numquam repellendus eligendi itaque dolorem impedit laborum voluptas suscipit. Totam.
				Praesentium, architecto animi labore qui ducimus quas optio accusantium? Delectus repellendus magni distinctio, autem nemo doloribus aliquid vero placeat quam itaque in facere iusto odit beatae maiores sint non libero.
				Excepturi, soluta quod quae ducimus ad dicta sequi enim dolor at tempora, reprehenderit voluptatum illum exercitationem inventore cum earum dolorum blanditiis doloribus quis laborum quasi consectetur, itaque neque! Vero, nam?
				Labore saepe corrupti eos quam totam in quos impedit! Ducimus, repellat nam quidem animi, omnis minima accusantium fuga placeat commodi eum provident delectus enim aspernatur officia velit facere iure assumenda?
				Suscipit repellendus esse aliquam soluta tempora a atque sed? Velit nemo adipisci eius, enim quam quibusdam amet, libero porro excepturi quisquam sit hic ratione iure doloremque rem tempore non ad.
				Perspiciatis voluptatem totam voluptate corporis eos blanditiis quasi, voluptates incidunt vitae illo, repudiandae amet ad ut sequi esse officiis aliquam. Eligendi facilis quo corporis sunt perspiciatis molestias, dicta optio vero!
				Corporis quo quisquam maiores, quaerat beatae vel hic sequi itaque esse fugiat corrupti inventore recusandae provident saepe dicta iste quod possimus natus necessitatibus. Ut adipisci autem ipsa reprehenderit aut eos?
				Dolore deserunt molestiae quas in, minima, praesentium esse consectetur reprehenderit modi nemo voluptatem maxime facere rerum quaerat aperiam. Hic ullam ipsa autem reprehenderit et, molestias maxime magnam amet laborum ab!
	</p>
</div>